services:
  traefik:
    container_name: traefik
    image: traefik:v3.3.3
    restart: always
    command:
      --log.level=ERROR
      --accesslog=true

      --providers.docker
      --providers.docker.exposedByDefault=false
      --providers.docker.endpoint=unix:///var/run/docker.sock
      --providers.file.directory=/etc/traefik/dynamic

      --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_MAIL}
      --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

      --entrypoints.web.address=:80
      --entryPoints.web.http.redirections.entryPoint.to=websecure
      --entryPoints.web.http.redirections.entryPoint.scheme=https
      --entrypoints.websecure.address=:443
      --entrypoints.websecure.forwardedHeaders.insecure=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/dynamic/traefik.yml
      - ./letsencrypt:/letsencrypt
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=false

  # Weather application services
  weather:
    container_name: weather
    restart: unless-stopped
    image: ${WEATHER_WEB_IMAGE}
    networks:
      - traefik
    volumes:
      - ./database.sqlite:/app/database/database.sqlite
    env_file:
      - ./.env.weather
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik

      - traefik.http.routers.weather.rule=Host(`${WEATHER_DOMAIN}`)
      - traefik.http.routers.weather.entrypoints=websecure
      - traefik.http.routers.weather.tls=true
      - traefik.http.routers.weather.tls.certresolver=letsencrypt
      - traefik.http.routers.weather.service=weather
      - traefik.http.services.weather.loadbalancer.server.port=80

  # Portfolio website
  portfolio:
    container_name: portfolio
    restart: unless-stopped
    image: ${PORTFOLIO_IMAGE}
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik

      - traefik.http.routers.portfolio.rule=Host(`${PORTFOLIO_DOMAIN}`)
      - traefik.http.routers.portfolio.entrypoints=websecure
      - traefik.http.routers.portfolio.tls=true
      - traefik.http.routers.portfolio.tls.certresolver=letsencrypt
      - traefik.http.routers.portfolio.service=portfolio
      - traefik.http.services.portfolio.loadbalancer.server.port=80

networks:
  traefik:
    name: traefik
    driver: bridge
